type CountryCode = {
  callingCode: string;
  isoCode: string;
};

export const countryCodes: CountryCode[] = [
  { callingCode: "1", isoCode: "us" },
  { callingCode: "44", isoCode: "gb" },
  { callingCode: "91", isoCode: "in" },
  { callingCode: "49", isoCode: "de" },
  { callingCode: "33", isoCode: "fr" },
  { callingCode: "81", isoCode: "jp" },
  { callingCode: "61", isoCode: "au" },
  { callingCode: "7", isoCode: "ru" },
  { callingCode: "86", isoCode: "cn" },
  { callingCode: "39", isoCode: "it" },
  { callingCode: "55", isoCode: "br" },
  { callingCode: "34", isoCode: "es" },
  { callingCode: "27", isoCode: "za" },
  { callingCode: "46", isoCode: "se" },
  { callingCode: "31", isoCode: "nl" },
  { callingCode: "41", isoCode: "ch" },
  { callingCode: "61", isoCode: "au" },
  { callingCode: "65", isoCode: "sg" },
  { callingCode: "90", isoCode: "tr" },
  { callingCode: "351", isoCode: "pt" },
  { callingCode: "43", isoCode: "at" },
  { callingCode: "45", isoCode: "dk" },
  { callingCode: "353", isoCode: "ie" },
  { callingCode: "972", isoCode: "il" },
  { callingCode: "62", isoCode: "id" },
  { callingCode: "63", isoCode: "ph" },
  { callingCode: "48", isoCode: "pl" },
  { callingCode: "420", isoCode: "cz" },
  { callingCode: "421", isoCode: "sk" },
  { callingCode: "359", isoCode: "bg" },
  { callingCode: "371", isoCode: "lv" },
  { callingCode: "370", isoCode: "lt" },
  { callingCode: "36", isoCode: "hu" },
  { callingCode: "45", isoCode: "dk" },
  { callingCode: "972", isoCode: "il" },
  { callingCode: "64", isoCode: "nz" },
  { callingCode: "673", isoCode: "bn" },
  { callingCode: "1", isoCode: "ca" },
  { callingCode: "1", isoCode: "jm" },
  { callingCode: "1", isoCode: "tt" },
  { callingCode: "1", isoCode: "bs" },
  { callingCode: "1", isoCode: "ky" },
  { callingCode: "1", isoCode: "ag" },
  { callingCode: "1", isoCode: "bb" },
  { callingCode: "1", isoCode: "dm" },
  { callingCode: "1", isoCode: "gd" },
  { callingCode: "1", isoCode: "ht" },
  { callingCode: "1", isoCode: "lc" },
  { callingCode: "1", isoCode: "ms" },
  { callingCode: "1", isoCode: "kn" },
  { callingCode: "1", isoCode: "vc" },
  { callingCode: "1264", isoCode: "ai" },
  { callingCode: "1268", isoCode: "ag" },
  { callingCode: "1284", isoCode: "vg" },
  { callingCode: "1340", isoCode: "vi" },
  { callingCode: "1473", isoCode: "gd" },
  { callingCode: "1787", isoCode: "pr" },
  { callingCode: "1758", isoCode: "lc" },
  { callingCode: "1868", isoCode: "tt" },
  { callingCode: "1869", isoCode: "kn" },
  { callingCode: "1876", isoCode: "jm" },
];
